language: rust
addons:
  apt:
    packages:
      # For dealing with MUSL.
      - musl-tools
matrix:
  fast_finish: true
  include:
    - rust: 1.29.0
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: stable
      env: TARGET=i686-unknown-linux-musl
    - rust: stable
      env: TARGET=x86_64-unknown-linux-musl
    - env: CROSS_TARGET=mips64-unknown-linux-gnuabi64
      rust: stable
      services: docker
      sudo: required

script: ci/script.sh
