[package]
name = "highway"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]

[dependencies]
byteorder = "1"

[dev-dependencies]
criterion = "0.2"
sha2 = "0.7"

[[bench]]
name = "highway"
harness = false
